version: '2'

services:
    djangotemplateproject_postgres_c:
        container_name: djangotemplateproject_postgres_c
        image: djangotemplateproject_init_postgres_i
        volumes:
            - djangotemplateproject_postgresql-volume:/var/lib/postgresql/9.5/main

volumes:
    djangotemplateproject_postgresql-volume:
        external: true