version: '2'

services:
    djangotemplateproject_django_c:
        container_name: djangotemplateproject_django_c
        image: djangotemplateproject_django_i
        ports:
            - 8000:8000
        volumes:
            - ../../../volumes/migrations:/usr/src/app/djangoproject/migrations
            - ../../../volumes/bower_components:/usr/src/app/djangoproject/static/bower_components
            - ../../../djangotemplateapplication:/usr/src/app/djangoproject/djangotemplateapplication
