FROM python:3

WORKDIR /usr/src/app

COPY ./resources/requirements.txt ./
RUN pip install --no-cache-dir -r requirements.txt

COPY ./   ./djangoproject/
RUN mkdir ./djangoproject/migrations &&\
    touch ./djangoproject/migrations/__init__.py
WORKDIR /usr/src/app/djangoproject

CMD python manage.py makemigrations &&\
    python manage.py migrate &&\

    python manage.py runserver 0.0.0.0:8000
