FROM python:3

WORKDIR /usr/src/app

COPY ./project/deployment/packagefiles/requirements.txt ./
RUN pip install --no-cache-dir -r requirements.txt

COPY ./   ./djangoproject/

RUN mkdir ./djangoproject/project/djangotemplateproject/mappings &&\
    mkdir ./djangoproject/project/djangotemplateproject/mappings/migrations &&\
    touch ./djangoproject/project/djangotemplateproject/mappings/migrations/__init__.py

WORKDIR /usr/src/app/djangoproject/project/djangotemplateproject

CMD python manage.py migrate &&\

    python manage.py shell < ../deployment/docker/init/scripts/django-create-admin.py &&\

    python manage.py runserver