version: '2'

services:
    djangotemplateproject_django_c:
        container_name: djangotemplateproject_django_c
        image: djangotemplateproject_django_i
        ports:
            - 8000:8000
        volumes:
            - ../../../resources/volumes/migrations:/usr/src/app/djangoproject/djangotemplateproject/mappings/migrations
            - ../../../djangotemplateproject/djangotemplateapplication:/usr/src/app/djangoproject/djangotemplateproject/djangotemplateapplication
            - ../../../djangotemplateproject/allauth_extension:/usr/src/app/djangoproject/djangotemplateproject/allauth_extension
