FROM python:3

RUN apt-get -y update

RUN apt-get -y install nodejs &&\
    apt-get -y install npm &&\
    ln -s /usr/bin/nodejs /usr/bin/node &&\
    npm install -g bower

WORKDIR /usr/src/app

COPY ./resources/requirements.txt ./
RUN pip install --no-cache-dir -r requirements.txt

COPY ./ ./djangoproject/
WORKDIR /usr/src/app/djangoproject

RUN python ./setup/rename/renameBowerPackages.py &&\
    python manage.py bower_install --allow-root

CMD python manage.py migrate &&\
    python manage.py makemigrations &&\
    python manage.py migrate &&\

    echo "from django.contrib.auth.models \
          import User; \ 
          User.objects.create_superuser('admin', 'admin@example.com', 'admin') \
         " | python manage.py shell &&\

    python manage.py runserver 0.0.0.0:8000
