FROM python:3

WORKDIR /usr/src/app

COPY ./resources/requirements.txt ./
RUN pip install --no-cache-dir -r requirements.txt

COPY ./ ./djangoproject/
WORKDIR /usr/src/app/djangoproject

CMD sleep 20s &&\

    python manage.py makemigrations &&\
    python manage.py migrate &&\

    python manage.py runserver