version: '2'

services:
    djangotemplateproject_django_c:
        container_name: djangotemplateproject_django_c
        image: djangotemplateproject_django_i
        ports:
            - 8000:8000
        volumes:
            - ../../../resources/volumes/bower_components:/usr/src/app/djangoproject/project/djangotemplateproject/mappings/static/bower_components
            - ../../../resources/vendor:/usr/src/app/djangoproject/project/djangotemplateproject/mappings/static/vendor
            - ../../../resources/volumes/migrations:/usr/src/app/djangoproject/project/djangotemplateproject/mappings/migrations
            - ../../../djangotemplateproject/djangotemplateapplication:/usr/src/app/djangoproject/project/djangotemplateproject/djangotemplateapplication
            - ../../../djangotemplateproject/extension_allauth:/usr/src/app/djangoproject/project/djangotemplateproject/extension_allauth
