FROM python:3

WORKDIR /usr/src/app

COPY ./resources/requirements.txt ./
RUN pip install --no-cache-dir -r requirements.txt

COPY ./ ./djangoproject/
WORKDIR /usr/src/app/djangoproject

CMD sleep 5s &&\

    echo "from django.contrib.auth.models \
          import User; \ 
          User.objects.create_superuser('admin', 'admin@example.com', 'admin') \
         " | python manage.py shell &&\
         
    python manage.py runserver