FROM ubuntu:16.04

RUN apt-get -y update
RUN apt-get -y install postgresql=9.5+173ubuntu0.1 postgresql-contrib=9.5+173ubuntu0.1

USER postgres

RUN service postgresql start &&\
    psql --command "CREATE DATABASE psqldb" &&\
    psql --command "CREATE USER psqluser WITH PASSWORD 'psql1234';" &&\
    psql --command "ALTER ROLE psqluser SET client_encoding TO 'utf8';" &&\
    psql --command "ALTER ROLE psqluser SET default_transaction_isolation TO 'read committed';" &&\
    psql --command "ALTER ROLE psqluser SET timezone TO 'UTC';" &&\
    psql --command "GRANT ALL PRIVILEGES ON DATABASE psqldb TO psqluser;"


