FROM ubuntu:16.04

RUN apt-get -y update
RUN apt-get -y install postgresql=9.5+173ubuntu0.1 postgresql-contrib=9.5+173ubuntu0.1

COPY ./setup/docker/init/scripts/ ./scripts/

USER postgres

RUN service postgresql start &&\

    bash ./scripts/postgres-create-db-and-user.sh


