FROM python:3

WORKDIR /usr/src/app

COPY ./resources/requirements.txt ./
RUN pip install --no-cache-dir -r requirements.txt

COPY ./   ./djangoproject/

RUN mkdir ./djangoproject/mappings &&\
    mkdir ./djangoproject/mappings/migrations &&\
    touch ./djangoproject/mappings/migrations/__init__.py

WORKDIR /usr/src/app/djangoproject

CMD python manage.py migrate &&\

    python manage.py shell < ./setup/docker/init/scripts/django-create-admin.py &&\

    python manage.py runserver